### ISSUE TITLE
Fix dependencies with security vulnerability

### ISSUE THREAD

**Issue by oasisvali** [openshiksha/openshiksha#9]

**Comment by Guzzler** [comment]
@oasisvali Let us finalize what we want to do about the rest of the vulnerabilities by the end of next week. I need to do a deeper dive to figure out where those are being used and if we can replace them or upgrade without breaking the existing codebase.

**Comment by oasisvali** [comment]
@Guzzler can you list which ones are remaining to be addressed?

**Comment by Guzzler** [comment]
closing due to the only two remaining issues are pycrypto and PIL which are dormant issues for now.
